spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:agrocortex}
    username: ${DB_USERNAME:agrocortex}
    password: ${DB_PASSWORD:agrocortex}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.agrocortex: INFO
    root: WARN
